export const BIOMES = [
  {
    id: 'forest',
    label: 'Forest',
    emoji: '🌲',
    colors: {
      primary:   '#4a7c2f',
      secondary: '#3d6626',
      border:    '#1e3a0f',
      highlight: '#6db84a',
      shadow:    '#2a4a1a',
    },
    proceduralParams: {
      edgeWidth: 2,
      dither: true,
      ditherStrength: 0.35,
      cornerStyle: 'organic',
      patternFn: 'checkerDither',
    },
  },
  {
    id: 'desert',
    label: 'Desert',
    emoji: '🏜️',
    colors: {
      primary:   '#d4a843',
      secondary: '#c49030',
      border:    '#7a5010',
      highlight: '#f0d080',
      shadow:    '#8b6914',
    },
    proceduralParams: {
      edgeWidth: 2,
      dither: true,
      ditherStrength: 0.4,
      cornerStyle: 'sharp',
      patternFn: 'checkerDither',
    },
  },
  {
    id: 'snow',
    label: 'Snow',
    emoji: '❄️',
    colors: {
      primary:   '#dce8f0',
      secondary: '#c8d8e8',
      border:    '#7090a8',
      highlight: '#ffffff',
      shadow:    '#a0b8cc',
    },
    proceduralParams: {
      edgeWidth: 2,
      dither: false,
      ditherStrength: 0.2,
      cornerStyle: 'rounded',
      patternFn: 'solid',
    },
  },
  {
    id: 'cave',
    label: 'Cave',
    emoji: '🪨',
    colors: {
      primary:   '#3d3540',
      secondary: '#2d2530',
      border:    '#1a1520',
      highlight: '#6b5f70',
      shadow:    '#221a25',
    },
    proceduralParams: {
      edgeWidth: 2,
      dither: true,
      ditherStrength: 0.25,
      cornerStyle: 'organic',
      patternFn: 'stonePattern',
    },
  },
  {
    id: 'ocean',
    label: 'Ocean',
    emoji: '🌊',
    colors: {
      primary:   '#2a5f8f',
      secondary: '#1e4a70',
      border:    '#0f2a48',
      highlight: '#5a9fdf',
      shadow:    '#1a3f6f',
    },
    proceduralParams: {
      edgeWidth: 2,
      dither: true,
      ditherStrength: 0.3,
      cornerStyle: 'rounded',
      patternFn: 'wavyPattern',
    },
  },
  {
    id: 'lava',
    label: 'Lava',
    emoji: '🌋',
    colors: {
      primary:   '#c43a00',
      secondary: '#a02800',
      border:    '#5a1000',
      highlight: '#ff8c42',
      shadow:    '#6b1e00',
    },
    proceduralParams: {
      edgeWidth: 2,
      dither: true,
      ditherStrength: 0.45,
      cornerStyle: 'sharp',
      patternFn: 'crackedPattern',
    },
  },
  {
    id: 'grassland',
    label: 'Grassland',
    emoji: '🌿',
    colors: {
      primary:   '#5a9b3a',
      secondary: '#4a8a2a',
      border:    '#2a5010',
      highlight: '#8adb5a',
      shadow:    '#3a6a20',
    },
    proceduralParams: {
      edgeWidth: 2,
      dither: true,
      ditherStrength: 0.3,
      cornerStyle: 'organic',
      patternFn: 'checkerDither',
    },
  },
  {
    id: 'dungeon',
    label: 'Dungeon',
    emoji: '🏰',
    colors: {
      primary:   '#5a5050',
      secondary: '#4a4040',
      border:    '#201818',
      highlight: '#8a7878',
      shadow:    '#302828',
    },
    proceduralParams: {
      edgeWidth: 2,
      dither: false,
      ditherStrength: 0.2,
      cornerStyle: 'sharp',
      patternFn: 'brickPattern',
    },
  },
]

export const BIOME_MAP = Object.fromEntries(BIOMES.map(b => [b.id, b]))
